#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

service_triggers() {
    procd_add_reload_trigger "repomirror"
}

reload_service() {
    /usr/share/repomirror/repomirror.sh
}

start_service() {
    /usr/share/repomirror/repomirror.sh
}
